# Generated by Django 4.1.7 on 2023-04-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexpay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_desc',
            field=models.CharField(default='default item', max_length=50),
        ),
    ]
