# Generated by Django 4.1.7 on 2023-04-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexpay', '0002_item_item_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='id',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.IntegerField(default='001', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
